version: '3'
services:
  apache:
    build: images/apache
    container_name: videoclub_apache
    ports:
      - "8002:80"
    expose:
      - "9000"
    volumes:
      - ./images/config/vhosts:/etc/apache2/sites-enabled
      - ./../:/home/wwwroot/videoclub
    depends_on:
      - php

  mariadb:
    image: mariadb:10.2
    container_name: videoclub_mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: images/php
    container_name: videoclub_php
    volumes:
      - ./../:/home/wwwroot/videoclub
    environment:
      - maildev_host=videoclub_maildev
    depends_on:
      - maildev
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: videoclub_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3307
    ports:
      - "8080:80"
    links:
      - mariadb

  maildev:
    image: djfarrelly/maildev
    container_name: videoclub_maildev
    ports:
      - "8003:80"

volumes:
  mariadbdata:
    driver: local
