get_all:
  methods: GET
  path: movies
  controller: service.controller.movie::getAll

get_by_id:
  methods: GET
  path: movie/{id}
  controller: service.controller.movie::getById

get_all_types:
  methods: GET
  path: movies/types/
  controller: service.controller.movie::getAllTypes

get_by_type:
  methods: GET
  path: movie/type/{typeId}
  controller: service.controller.movie::getByType

rent_calculate:
  methods: POST
  path: rent/calculate
  controller: service.controller.movie::rentCalculate
